# Utilisez une image de base avec un serveur web léger
FROM nginx:alpine

# Copiez les fichiers du projet dans le dossier du serveur web
COPY . /usr/share/nginx/html

# Définition du port exposé par le conteneur
EXPOSE 80
